# Introduction

# Definizione teorica del costrutto

Il costrutto che abbiamo deciso di prendere in analisi è quello dell’attenzione sostenuta, una sfaccettatura del costrutto più generale di ”attenzione". La letteratura analizzata, e in particolare Oken et al. (2006), la definisce (citando Davies e Parasuraman, 1982; Parasuraman, 1998) la capacità di mantenere l'attenzione su un compito per un periodo di tempo. Una definizione sperimentale del costrutto è fornita dai lavori di Mackworth (1948), che, studiando la performance in compiti di monitoraggio prolungato, introdusse il concetto di vigilanza mostrando il “vigilance decrement”, ovvero il deterioramento progressivo della capacità di mantenere l’attenzione sostenuta testimoniato dal calo del rilevamento dei segnali critici durante lo svolgimento di compiti continuativi. La letteratura utilizza, però, la medesima definizione per i termini vigilance, alertness e sustained attention, rendendo necessaria una chiarificazione. Langner e Eickhoff (2012) la descrivono, in maniera più articolata, come una facoltà mentale multicomponente, che coinvolge una combinazione di processi sostenuti e ricorrenti, che sottendono al mantenimento dell’attivazione fisiologica (arousal), e processi transitori, che implicano il riorientamento dell'attenzione in funzione dell'obiettivo. Infine, il modello di Thomson et al. (2015) interpreta il decremento dell’attenzione, precedentemente citato, combinando due diverse teorie: la teoria delle risorse attentive (Smallwood & Schooler, 2006) e il fallimento del controllo (McVay & Kane, 2010). Il costrutto viene quindi definito come conseguenza di un indebolimento dei meccanismi di controllo delle risorse cognitive, spesso associato a fenomeni di mind wandering (spostamento spontaneo dell’attenzione verso pensieri interni) durante compiti prolungati. Nel complesso la letteratura presa in analisi ci ha consentito di definire l’attenzione sostenuta come un costrutto essenziale da tenere in considerazione nello studio dei processi attentivi, caratterizzato dal mantenimento della performance nel tempo e dalla presenza del decremento attentivo e dei fenomeni da esso causati.

## Definizione Operativa

1.1. Definizione Operativa Il test sviluppato è a prestazione tipica, ossia misura la prestazione abituale degli individui, in questo caso a livello attentivo, sulla base della percezione degli stessi delle proprie performance nella vita di tutti i giorni. Non misura, dunque, la durata massima di mantenimento dell’attenzione, ma le capacità che in media si ritiene di possedere in questo ambito. Per la stesura ci siamo ispirati a due test già esistenti in letteratura: Attention Control Scale (ACS) ed Everyday Life Attention Scale (ELAS). Dal primo abbiamo ricavato un insieme di item sull’attenzione sostenuta e alternata, da cui abbiamo estrapolato solo quelli riguardanti il costrutto di nostro interesse, formulandone ulteriori ad essi ispirati; il secondo ci ha dato l’idea di inserire nel test compiti che riguardano la vita quotidiana di ogni individuo, per arricchirlo e renderlo più accurato. Il test è sviluppato con una modalità di risposta su scala Likert a 5 punti (da “poco vero” a “completamente vero”), un buon compromesso vista la brevità del test (dunque non appesantisce cognitivamente) e la precisione che fornisce, con la presenza di un “punto centrale”. La scala è, infine, compatibile con le analisi psicometriche richieste in questa esercitazione.
